# Generated by Django 4.1.4 on 2023-01-02 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='ending_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='starting_at',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 1, 2), null=True),
        ),
    ]
