# Generated by Django 4.1.4 on 2023-01-02 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_orgunit_description_alter_orgunit_ending_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='ending_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='starting_at',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
