# Generated by Django 4.1.4 on 2023-01-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_supervisor_worker_supervisor_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='company',
            field=models.CharField(choices=[('KYN-BE', 'Kyndryl BE'), ('PIS-BE', 'PI-SQUARE')], db_index=True, default=1, max_length=6),
            preserve_default=False,
        ),
    ]
