# Generated by Django 4.1.4 on 2023-01-05 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_worker_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='type',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='manager',
        ),
        migrations.CreateModel(
            name='WorkerSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('HI', 'Hierarchical Manager'), ('FU', 'Functional Manager')], db_index=True, max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('starting_at', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('ending_at', models.DateField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.supervisor')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.worker')),
            ],
        ),
        migrations.AddField(
            model_name='supervisor',
            name='supervising_group',
            field=models.ManyToManyField(related_name='worker', through='teams.WorkerSupervisor', to='teams.worker'),
        ),
    ]
