# Generated by Django 4.1.4 on 2023-01-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0002_alter_objective_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='ref_period',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], db_index=True, max_length=5),
        ),
    ]
