# Generated by Django 4.1.4 on 2023-01-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0005_objective_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='domain',
            field=models.CharField(choices=[('Education', 'Education'), ('Execution', 'Execution'), ('Template', 'Template')], default='EXE', max_length=10),
        ),
        migrations.AddField(
            model_name='objective',
            name='subject',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
