# Generated by Django 4.1.4 on 2023-01-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0006_objective_domain_objective_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='domain',
            field=models.CharField(choices=[('Education', 'Education'), ('Execution', 'Execution'), ('Template', 'Template')], default='Execution', max_length=10),
        ),
    ]
