# Generated by Django 4.1.4 on 2023-01-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0008_alter_objective_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='subject',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
