# Generated by Django 4.1.4 on 2023-01-31 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0009_alter_objective_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='score',
        ),
        migrations.CreateModel(
            name='ObjectiveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_result_set', models.TextField(blank=True, null=True)),
                ('comment_result_approval', models.TextField(blank=True, null=True)),
                ('calibration_result_midyear', models.CharField(choices=[('UNSAT', 'Unsat'), ('BELOW', 'Below Joblevel'), ('JOB', 'Joblevel'), ('ABOVE', 'Above Joblevel'), ('EXCEP', 'Exceptional')], max_length=10)),
                ('score_result_midyear', models.CharField(choices=[('UNSAT', 'Unsat'), ('BELOW', 'Below Joblevel'), ('JOB', 'Joblevel'), ('ABOVE', 'Above Joblevel'), ('EXCEP', 'Exceptional')], max_length=10)),
                ('comment_result_midyear', models.TextField(blank=True, null=True)),
                ('calibration_result_endyear', models.CharField(choices=[('UNSAT', 'Unsat'), ('BELOW', 'Below Joblevel'), ('JOB', 'Joblevel'), ('ABOVE', 'Above Joblevel'), ('EXCEP', 'Exceptional')], max_length=10)),
                ('score_result_endyear', models.CharField(choices=[('UNSAT', 'Unsat'), ('BELOW', 'Below Joblevel'), ('JOB', 'Joblevel'), ('ABOVE', 'Above Joblevel'), ('EXCEP', 'Exceptional')], max_length=10)),
                ('comment_result_endyear', models.TextField(blank=True, null=True)),
                ('setobjectives_at', models.DateField(blank=True, null=True)),
                ('objectives_approval_at', models.DateField(blank=True, null=True)),
                ('midyear_at', models.DateField(blank=True, null=True)),
                ('endyear_at', models.DateField(blank=True, null=True)),
                ('endyear_approval_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objective', to='objectives.objective', verbose_name='objective_result')),
            ],
        ),
    ]
