# Generated by Django 4.1.4 on 2023-01-31 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0010_remove_objective_score_objectiveresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='endyear_approval_at',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='endyear_at',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='midyear_at',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='objectives_approval_at',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='setobjectives_at',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='updated_at',
        ),
    ]
