# Generated by Django 4.1.4 on 2023-02-17 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0008_worker_account'),
        ('objectives', '0011_remove_objective_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('Execution', 'Execution'), ('Education', 'Education'), ('Template', 'Template')], default='Execution', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objDetails_employee', to='teams.worker', verbose_name='employee')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objDetails_owner', to='teams.worker', verbose_name='owner')),
            ],
        ),
        migrations.CreateModel(
            name='ObjMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_period', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], db_index=True, max_length=5)),
                ('stage', models.CharField(choices=[('START', 'Start Objectives'), ('SET-OBJ', 'Set Objectives'), ('RUN-OBJ', 'Execute Objectives'), ('CALIB-MIDYEAR', 'Calibration for MidYear'), ('MIDYEAR', 'MidYear'), ('CALIB-ENDYEAR', 'Calibration for MidYear'), ('ENDYEAR', 'EndYear'), ('CLOSE-OBJ', 'Close')], db_index=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objMaster_employee', to='teams.worker', verbose_name='employee')),
                ('obj_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objMaster', to='objectives.objdetails', verbose_name='obj_details')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objMaster_owner', to='teams.worker', verbose_name='owner')),
            ],
        ),
        migrations.CreateModel(
            name='ObjDetailsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_result_set', models.TextField(blank=True, null=True)),
                ('comment_result_approval', models.TextField(blank=True, null=True)),
                ('objectives_approval_at', models.DateField(blank=True, null=True)),
                ('calibration_result_midyear', models.CharField(choices=[('UNSAT', 'Unsat'), ('BELOW', 'Below Joblevel'), ('JOB', 'Joblevel'), ('ABOVE', 'Above Joblevel'), ('EXCEP', 'Exceptional')], max_length=10)),
                ('midyear_at', models.DateField(blank=True, null=True)),
                ('score_result_midyear', models.CharField(choices=[('UNSAT', 'Unsat'), ('BELOW', 'Below Joblevel'), ('JOB', 'Joblevel'), ('ABOVE', 'Above Joblevel'), ('EXCEP', 'Exceptional')], max_length=10)),
                ('comment_result_midyear', models.TextField(blank=True, null=True)),
                ('calibration_result_endyear', models.CharField(choices=[('UNSAT', 'Unsat'), ('BELOW', 'Below Joblevel'), ('JOB', 'Joblevel'), ('ABOVE', 'Above Joblevel'), ('EXCEP', 'Exceptional')], max_length=10)),
                ('endyear_at', models.DateField(blank=True, null=True)),
                ('score_result_endyear', models.CharField(choices=[('UNSAT', 'Unsat'), ('BELOW', 'Below Joblevel'), ('JOB', 'Joblevel'), ('ABOVE', 'Above Joblevel'), ('EXCEP', 'Exceptional')], max_length=10)),
                ('comment_result_endyear', models.TextField(blank=True, null=True)),
                ('endyear_approval_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objDetailsResult', to='objectives.objdetails', verbose_name='objective_result')),
            ],
        ),
    ]
